---
- name: Create Project for Architecture Demo
  hosts: localhost

  tasks:

    - name: Create Architecture Demo Project
      ansible.controller.project:
        name: "DO417 Demo Project"
        description: "DO417 Demo Project from Github"
        organization: "Red Hat Training"
        scm_update_on_launch: "no"
        scm_url: https://github.com/tmichett/DO417_Demo.git
        scm_type: git
        scm_branch: main
        controller_username: admin
        controller_password: redhat
        controller_host: https://controller.lab.example.com
        validate_certs: false
        state: present
