---
- name: Create Job Template
  hosts: localhost

  tasks:

    - name: Create Job Template
      ansible.controller.job_template:
        name: "DO417 Architecture Demo - Playbook"
        description: "Demo of Architecture for Controller"
        organization: Red Hat Training
        project: DO417 Demo Project
        inventory: DO417 Demo Inventory
        job_type: run
        playbook: "Demos/CH1/Architecture/win_ping.yml"
        credential: devops
        controller_username: admin
        controller_password: redhat
        controller_host: https://controller.lab.example.com
        validate_certs: false
        state: present
