---
### Create Ansible Controller Demo
- import_playbook: Create_Organization.yml
- import_playbook: Create_Project.yml
- import_playbook: Setup_Inventory.yml
- import_playbook: Create_Job_Template.yml

